apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-app-pipeline
serialPipeline:
  stages:
  - targetId: dev-env
  - targetId: prod-env
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: cicd-pipeline-sa@cicd-devops-demos.iam.gserviceaccount.com
run:
  location: projects/cicd-devops-demos/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-env
requireApproval: true
executionConfigs:
- usages:
  - RENDER
  - DEPLOY
  serviceAccount: cicd-pipeline-sa@cicd-devops-demos.iam.gserviceaccount.com
run:
  location: projects/cicd-devops-demos/locations/us-east1
