steps:
  # 1. Lint the Code
  - name: 'python:3.12-slim'
    id: 'Lint'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install ruff
        ruff check src/ tests/

  # 2. Run Unit Tests
  - name: 'python:3.12-slim'
    id: 'Test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install pytest httpx
        pytest tests/

  # 3. Build the Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-repo/basic-fastapi-app:$SHORT_SHA', '.']

  # 4. Push the Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-repo/basic-fastapi-app:$SHORT_SHA']

  # 5. Scan for Vulnerabilities in the image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'VulnerabilityScan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        image='${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-repo/basic-fastapi-app:$SHORT_SHA'
        echo "Scanning image: $image"
        
        # Start the scan and capture the SCAN id
        scan_name=$(gcloud artifacts docker images scan "$image" \
          --format='value(response.scan)' \
          --remote)
        
        echo "Scan requested: $scan_name"
        gcloud artifacts docker images list-vulnerabilities "$scan_name" --format="table(vulnerability.effectiveSeverity,vulnerability.packageIssue[0].affectedPackage)" || true

  # 6. Create a Release in Cloud Deploy (Hands off to CD)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy'
    entrypoint: gcloud
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=demo-app-pipeline'
      - '--region=${_REGION}'
      - '--images=basic-fastapi-app=${_REGION}-docker.pkg.dev/$PROJECT_ID/demo-repo/basic-fastapi-app:$SHORT_SHA'

substitutions:
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY