apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: basic-fastapi-app
  annotations:
    run.googleapis.com/binary-authorization: default
spec:
  template:
    spec:
      containers:
      - image: basic-fastapi-app:latest